import { readdir, readFile, writeFile } from 'fs/promises';
import { join } from 'path';
import { ensureDirectoryExists, toKebabCase } from './utils/shared';

interface IconCategoryData {
  name: string;
  category: string;
  filled?: boolean;
}

interface IconsByCategory {
  [categoryId: string]: string[];
}

export async function generateIconsByCategory(): Promise<void> {
  console.log('📁 Generating icons-by-category...');

  try {
    // Read icon-category.json
    const iconCategoryPath = join('out', 'icon-category.json');
    const iconCategoryData: Record<string, IconCategoryData> = JSON.parse(
      await readFile(iconCategoryPath, 'utf-8'),
    );

    // Group icons by category
    const iconsByCategory: IconsByCategory = {};

    for (const [iconName, data] of Object.entries(iconCategoryData)) {
      const categoryId = toKebabCase(data.category);

      if (!iconsByCategory[categoryId]) {
        iconsByCategory[categoryId] = [];
      }

      iconsByCategory[categoryId].push(iconName);
    }

    // Sort icons alphabetically within each category
    for (const category in iconsByCategory) {
      iconsByCategory[category].sort();
    }

    // Generate TypeScript file with actual data
    const entries = Object.entries(iconsByCategory)
      .map(([categoryId, icons]) => {
        const iconList = JSON.stringify(icons);
        return `  '${categoryId}': ${iconList as string}`;
      })
      .join(',\n');

    const content = `// Auto-generated by scripts/generateIconsByCategory.ts
// Do not edit manually!

/**
 * Mapping of category IDs to arrays of icon names
 * Generated from icon-category.json
 *
 * @example
 * import iconsByCategory from '@pelatform/icons/icons-by-category'
 *
 * // Get all icons in a category
 * const animalsIcons = iconsByCategory['animals'] // ['cat', 'dog', ...]
 *
 * // Filter icons by category
 * const filterIcons = (categoryId: string) => {
 *   return iconsByCategory[categoryId] || []
 * }
 */
const iconsByCategory: Record<string, string[]> = {
${entries}
};

export default iconsByCategory;
`;

    // Write to src/icons-by-category.ts
    const outputPath = join('src', 'icons-by-category.ts');
    await ensureDirectoryExists('src');
    await writeFile(outputPath, content, 'utf-8');

    console.log(
      `✅ Generated icons-by-category with ${Object.keys(iconsByCategory).length} categories`,
    );
  } catch (error) {
    console.error('❌ Error generating icons-by-category:', error);
    throw error;
  }
}

// Run the script
generateIconsByCategory().catch((error) => {
  console.error('❌ Unexpected error:', error);
  process.exit(1);
});
